name: Update all versions (scheduled)

on:
  schedule:
    - cron: "37 4 * * 5"

permissions:
  contents: write

jobs:
  update-linux:
    uses: ./.github/workflows/update-version.yml
    with:
      platform: linux
  update-darwin:
    uses: ./.github/workflows/update-version.yml
    with:
      platform: darwin
